services:
  cloud-trade-api:
    build:
      context: .
      dockerfile: app/src/TradeApi/Dockerfile
    image: cloud-trade-api:local
    container_name: cloud-trade-api
    ports:
      - "5000:8080"
    environment:
      APP_VERSION: "0.1.0-compose"
      APP_ENVIRONMENT: "dev"
      APP_LOG_LEVEL: "debug"